language: python
os: linux
dist: bionic
#if: branch = master or tag IS present
python: 3.6

# important: with limited depth the tags are not cloned properly - the PBR does not work
git:
   depth: false

services:
    - docker

jobs:
  include:
    - stage: Test on Python 3.6
      before_script:
          - ./setup.py install
          - pip install docker-compose
          - pip show rkd
      script:
          - rkd :test
