language: python
os: linux
dist: bionic
#if: branch = master or tag IS present
python: 3.6

# important: with limited depth the tags are not cloned properly - the PBR does not work
git:
   depth: false

services:
    - docker

before_install:
  - './.travis/main.sh'

jobs:
  include:
    - stage: "Test on Python 3.6 (docker-compose: 1.25)"
      before_script:
          - ./setup.py install
          - pip install docker-compose==1.25.0
          - pip show rkd
      script:
          - rkd :test

    - stage: "Test on Python 3.8 (docker-compose: 1.25)"
      python: 3.8
      before_script:
          - ./setup.py install
          - pip install docker-compose==1.25.0
          - pip show rkd
      script:
          - rkd :test

    - stage: "Test on Python 3.8, LATEST docker-compose and LATEST RKD"
      python: 3.8
      before_script:
          - ./setup.py install
          - pip install --upgrade docker-compose rkd
          - pip show docker-compose
          - pip show rkd
      script:
          - rkd :test
