language: python
python: 3.6
services:
    - docker

jobs:
  include:
    - stage: Check if environment starts
      before_script:
          - sudo /bin/bash -c 'echo "127.0.0.1 health.test.localhost" >> /etc/hosts'
      script:
          - make start DETACH=true
          - sleep 15
          - docker ps
          - curl -f -v http://health.test.localhost/some-test/
