version: "2.0"
services:
    tech_deployer:
        image: wolnosciowiec/thin-deployer
        volumes:
            - "./apps/continuous-deployment/deployer.yml:/root/.deployer.yml"
            - "./:/deployer-root"
            - "/var/run/docker.sock:/var/run/docker.sock"
        environment:
            # gateway configuration
            - VIRTUAL_HOST=deploy.${MAIN_DOMAIN}${DOMAIN_SUFFIX}
            - VIRTUAL_PORT=8012
