version: '2'
services:
    #
    # Docker admin panel
    #
    portainer:
        image: portainer/portainer
        command: -H unix:///var/run/docker.sock
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./data/portainer:/data
        expose:
            - "9000"
        environment:
            # gateway configuration
            - VIRTUAL_HOST=a2.${MAIN_DOMAIN}${DOMAIN_SUFFIX}
            - VIRTUAL_PORT=9000

    healthcheck:
        image: wolnosciowiec/infracheck
        command: " --directory=/data --server-path-prefix=/some-prefix"
        volumes:
            - "./apps/healthchecks:/data"
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
        expose:
            - "8000"
        environment:
            # gateway configuration
            - VIRTUAL_HOST=health.${MAIN_DOMAIN}${DOMAIN_SUFFIX}
            - VIRTUAL_PORT=8000
