version: '2'
services:
    #
    # Docker admin panel
    #
    portainer:
        image: portainer/portainer
        command: -H unix:///var/run/docker.sock
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./data/portainer:/data
        expose:
            - "9000"
        environment:
            # gateway configuration
            - VIRTUAL_HOST=a2.${MAIN_DOMAIN}${DOMAIN_SUFFIX}
            - VIRTUAL_PORT=9000
            - LETSENCRYPT_HOST=a2.${MAIN_DOMAIN}${DOMAIN_SUFFIX}
            - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
        labels:
            com.centurylinklabs.watchtower.enable: true
            org.riotkit.useMaintenanceMode: false
